[app]

app_title = "Customer-Base Analysis App"

app_description = "This app is for analyzing customer-base purchase pattern and future value (Customer Lifetime Value)"

app_overview_definition = """
**App Functions**
* Determine high value customers
* Identify customer inactivity
* Analyze customer purchase pattern
* Predict customer lifetime value
* Predict industry growth
\n
**What is Customer Lifetime Value?**
\n
Customer lifetime value is the **present value** of the **future\
(net) cash flows** associated with a particular customer.
\n
**What is RFM Metrics?**
\n
RFM Metrics are metrics for measuring customer purchase characteristics.
* **Recency**: the age of the customer at the moment of his last purchase, \
which is equal to the duration between a customer’s first purchase and their last purchase.
* **Frequency**: the number of periods in which the customer has made a repeat purchase.
* **T**: the age of the customer at the end of the period under study, \
which is equal to the duration between a customer’s first purchase and the last day in the dataset.
* **Monetary**: the customer's average transaction value.
"""

app_overview_guide = """
**Model Explanation**
\n
This app uses two of the statistical models from the "Buy Till You Die (BTYD)" called BG/NBD Model and Gamma-Gamma Model.
* **BG/NBD Model** is statistical model designed to capture the behavioral characteristics of \
non-contractual customers (when the company is now able to directly observe when a customer stops being a customer).
* The purpose of BG/NBD Model is to calculate the probability of customer being inactive and to predict \
the number of customer's future purchases.
* The purpose of Gamma-Gamma Model is to predict the customer's future average transaction value.
\n
**Evaluation Metrics**
\n
* **MAE** is the average error of the predicted model
* **RMSE** is the root average error of the predicted model
* **Chi-Square test** is a test to identify if there are significant difference between model and actual data.
* **Pearson Correlation** is the correlation between frequency and monetary. \
The closer to zero the more appropriate the data for the model because 
model assumes there are no dependency between frequency and monetary
* **MAPE** is the average percentage error of the prediction.\
is used to calculate error between predicted and actual average transaction value
"""

app_conceptual_model_image = './references/Conceptual Model.png'

app_dataset = './references/Dataset.csv'